//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JAVADBEntities : DbContext
    {
        public JAVADBEntities()
            : base("name=JAVADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdminUser> tblAdminUsers { get; set; }
        public virtual DbSet<tblAppVersion> tblAppVersions { get; set; }
        public virtual DbSet<tblBlock> tblBlocks { get; set; }
        public virtual DbSet<tblCouponGroup> tblCouponGroups { get; set; }
        public virtual DbSet<tblCoupon> tblCoupons { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblEventArtist> tblEventArtists { get; set; }
        public virtual DbSet<tblEventLayoutBlock> tblEventLayoutBlocks { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<tblEventVolunteer> tblEventVolunteers { get; set; }
        public virtual DbSet<tblLayout> tblLayouts { get; set; }
        public virtual DbSet<tblMailLog> tblMailLogs { get; set; }
        public virtual DbSet<tblOrderCoupon> tblOrderCoupons { get; set; }
        public virtual DbSet<tblOTP> tblOTPS { get; set; }
        public virtual DbSet<tblPastEvent> tblPastEvents { get; set; }
        public virtual DbSet<tblReleaseLog> tblReleaseLogs { get; set; }
        public virtual DbSet<tblSeat> tblSeats { get; set; }
        public virtual DbSet<tblSeatRow> tblSeatRows { get; set; }
        public virtual DbSet<tblSeatSelection> tblSeatSelections { get; set; }
        public virtual DbSet<tblSeatSelectionsLog> tblSeatSelectionsLogs { get; set; }
        public virtual DbSet<tblTicketOrder> tblTicketOrders { get; set; }
        public virtual DbSet<tblTicket> tblTickets { get; set; }
        public virtual DbSet<tblTier> tblTiers { get; set; }
        public virtual DbSet<tblTierCoupon> tblTierCoupons { get; set; }
        public virtual DbSet<tblVenue> tblVenues { get; set; }
        public virtual DbSet<tblVolunteer> tblVolunteers { get; set; }
        public virtual DbSet<TempOrder> TempOrders { get; set; }
        public virtual DbSet<TempTicket> TempTickets { get; set; }
        public virtual DbSet<VOBARegistration> VOBARegistrations { get; set; }
    }
}
