//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBlock()
        {
            this.tblEventLayoutBlocks = new HashSet<tblEventLayoutBlock>();
            this.tblSeatRows = new HashSet<tblSeatRow>();
        }
    
        public int BlockID { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public string BlockNumber { get; set; }
    
        public virtual tblLayout tblLayout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventLayoutBlock> tblEventLayoutBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeatRow> tblSeatRows { get; set; }
    }
}
