//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCouponGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCouponGroup()
        {
            this.tblCoupons = new HashSet<tblCoupon>();
            this.tblTierCoupons = new HashSet<tblTierCoupon>();
        }
    
        public int CouponGroupID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> NoOfCoupons { get; set; }
        public string DiscountIn { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Tiers { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoupon> tblCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTierCoupon> tblTierCoupons { get; set; }
    }
}
