//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCoupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCoupon()
        {
            this.tblOrderCoupons = new HashSet<tblOrderCoupon>();
        }
    
        public int CouponID { get; set; }
        public Nullable<int> CouponGroupID { get; set; }
        public string CouponCode { get; set; }
        public string DiscountIn { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblCouponGroup tblCouponGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderCoupon> tblOrderCoupons { get; set; }
    }
}
