//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblEventLayoutBlocks = new HashSet<tblEventLayoutBlock>();
            this.tblEventVolunteers = new HashSet<tblEventVolunteer>();
            this.tblSeatSelections = new HashSet<tblSeatSelection>();
            this.tblTickets = new HashSet<tblTicket>();
        }
    
        public int EventID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public string EventName { get; set; }
        public string EventType { get; set; }
        public string EventLanguage { get; set; }
        public string EventPlaytime { get; set; }
        public string EventDurationType { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ShowTime { get; set; }
        public string EventBanner { get; set; }
        public string EventMainBanner { get; set; }
        public string EventHomeBanner { get; set; }
        public string LocationTracker { get; set; }
        public string EventDescription { get; set; }
        public string EventTNC { get; set; }
        public string AgeGroup { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string BookingType { get; set; }
        public Nullable<decimal> ProcessingFee { get; set; }
        public Nullable<int> TicketStock { get; set; }
        public string Status { get; set; }
        public Nullable<int> PercentEBSeats { get; set; }
        public string EarlyBirdTicketSelection { get; set; }
        public Nullable<int> TicketsAvailable { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
        public Nullable<decimal> EBTicketPrice { get; set; }
        public Nullable<int> EBMinTicketOrder { get; set; }
        public Nullable<int> EBMaxTicketOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventLayoutBlock> tblEventLayoutBlocks { get; set; }
        public virtual tblLayout tblLayout { get; set; }
        public virtual tblVenue tblVenue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventVolunteer> tblEventVolunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeatSelection> tblSeatSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicket> tblTickets { get; set; }
    }
}
