//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMailLog
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string MailContent { get; set; }
    }
}
