//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderCoupon
    {
        public int OrderCouponID { get; set; }
        public Nullable<int> CouponID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblCoupon tblCoupon { get; set; }
        public virtual tblTicketOrder tblTicketOrder { get; set; }
    }
}
