//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPastEvent
    {
        public int PastEventID { get; set; }
        public string EventName { get; set; }
        public string ImagePath { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
