//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeat()
        {
            this.tblSeatSelections = new HashSet<tblSeatSelection>();
        }
    
        public int SeatID { get; set; }
        public Nullable<int> SeatRowID { get; set; }
        public string SeatNumber { get; set; }
        public string Status { get; set; }
    
        public virtual tblSeatRow tblSeatRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeatSelection> tblSeatSelections { get; set; }
    }
}
