//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeatSelection
    {
        public int SeatSelectionID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblSeat tblSeat { get; set; }
        public virtual tblTicket tblTicket { get; set; }
    }
}
