//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTicket()
        {
            this.tblSeatSelections = new HashSet<tblSeatSelection>();
        }
    
        public int TicketID { get; set; }
        public string TicketNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaypalOrderID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeatSelection> tblSeatSelections { get; set; }
    }
}
