//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrder
    {
        public int TempID { get; set; }
        public string PaypalID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EventID { get; set; }
    }
}
