//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOBARegistration
    {
        public int RegistrationID { get; set; }
        public string ParentName { get; set; }
        public string ParentEmail { get; set; }
        public string ParentMobile { get; set; }
        public string ChildName { get; set; }
        public string ChildDOB { get; set; }
        public Nullable<bool> TermsAccepted { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentStatus { get; set; }
        public string PaypalOrderID { get; set; }
        public string Intent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
